### ISSUE TITLE
Create TrainingPrograms/Detail/{id} View

### ISSUE THREAD

**Issue by caseywreed** [NSS-Team-Delta/Delta-Workforce-Management#47]
### Feature Description
The `TrainingPrograms/Detail/{id}` route will provide the user with a detailed view of a single Training Program.  The `Detail()` method on the `TrainingPrograms` controller will accept an argument of a `TrainingProgram` object and the following properties of that object will be displayed in this view:

```
Name - [string]
Description - [string]
Start Date - [DateTime] [Maybe we can use a DatePicker?]
End Date - [DateTime] [Maybe we can use a DatePicker?]
Current Capacity - [int]
Maximum Capacity - [int]
List of Currently Associated Employees - [List<Employees>]
```

### Requirement to Fulfill
#10 

### Notes

**Comment by tshavor** [comment]
LGTM
